### ISSUE TITLE
Why didnt you add the ioctl driver for this.

### ISSUE THREAD

**Issue by NameNotTakenYAY** [Joona70/pubg-private#1]
Why didnt you add the ioctl driver for this. Im going to assume pasters but still please respond thanks!

**Comment by Joona70** [comment]
get it from the other repo, retard.

**Comment by NameNotTakenYAY** [comment]
I know to get it from the other repo you didn't have  to be rude about it?

**Comment by Joona70** [comment]
> 
> 
> I know to get it from the other repo you didn't have to be rude about it?

if you would have known, you would have not asked.
